const eventStatuses = {
    notifications: {
        NOTIFICATIONS_LIST_LOADED: "NOTIFICATIONS_LIST_LOADED",
        NOTIFICATIONS_LIST_NOT_FOUND: "NOTIFICATIONS_LIST_NOT_FOUND",
        SINGLE_NOTIFICATION_ADDED: "SINGLE_NOTIFICATION_ADDED",
        SINGLE_NOTIFICATION_ADDING_FAILED: "SINGLE_NOTIFICATION_ADDING_FAILED",
        MULTI_NOTIFICATIONS_ADDED: "MULTI_NOTIFICATIONS_ADDED",
        MULTI_NOTIFICATIONS_ADDING_FAILED: "MULTI_NOTIFICATIONS_ADDING_FAILED",
        SINGLE_NOTIFICATION_LOADED: "SINGLE_NOTIFICATION_LOADED",
        SINGLE_NOTIFICATION_NOT_FOUND: "SINGLE_NOTIFICATION_NOT_FOUND",
        NOTIFICATION_SUCCESSFULLY_EDITED: "NOTIFICATION_SUCCESSFULLY_EDITED",
        NOTIFICATION_EDITING_FAILED: "NOTIFICATION_EDITING_FAILED",
        NOTIFICATION_SUCCESSFULLY_REMOVED: "NOTIFICATION_SUCCESSFULLY_REMOVED",
        NOTIFICATION_REMOVING_FAILED: "NOTIFICATION_REMOVING_FAILED",
        AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
        RESET_STATUS: "RESET_STATUS",
    },
};

export default eventStatuses;
